import os
from typing import Optional, Any
import re
import asyncio
import requests

from llama_index.core.workflow import (
    StartEvent,
    StopEvent,
    step,
    Workflow,
    Context,
)
from llama_index.core import SummaryIndex
from llama_index.core.schema import Document
from llama_index.core.prompts import PromptTemplate
from llm_provider import build_llm
from llama_index.core.llms import LLM
from llama_index.core.base.base_retriever import BaseRetriever
from typing import List

from llama_index.core.schema import NodeWithScore
from llama_index.core.workflow import (
    Event,
)

from dotenv import load_dotenv

load_dotenv()


class RetrieveEvent(Event):
    """Retrieve event (gets retrieved nodes)."""

    retrieved_nodes: List[NodeWithScore]


class WebSearchEvent(Event):
    """Web search event."""

    relevant_chunks: List[str]  # not used, just used for pass through


class QueryEvent(Event):
    """Query event. Queries given the individually-graded relevant chunks
    (kept as a list, not pre-joined, so query_result() can cite each one
    separately) and the web search text."""

    relevant_chunks: List[str]
    search_text: str


class TokenEvent(Event):
    """A single streamed token/delta from the final answer generation.

    Emitted via `ctx.write_event_to_stream()` from `query_result()` so a
    caller can render the answer as it is generated by consuming
    `handler.stream_events()` (see app.py), instead of waiting for the whole
    workflow to finish.
    """

    delta: str


def _tag_web_search_results(search_text: str) -> str:
    """Prefix each FireCrawl result block with a `[Web Source: <url>]` tag.

    `_firecrawl_search()` returns blocks shaped like
    "Title: ...\\nDescription: ...\\nURL: ...\\n" separated by "\\n---\\n".
    This pulls the URL out of each block and tags the block with it so that
    downstream prompting (in `query_result()`) can clearly attribute context
    to the web source it came from, and the model can cite it.
    """
    if not search_text.strip():
        return search_text

    tagged_blocks = []
    for block in search_text.split("\n---\n"):
        block = block.strip()
        if not block:
            continue
        match = re.search(r"URL:\s*(\S+)", block)
        url = match.group(1) if match else "unknown"
        tagged_blocks.append(f"[Web Source: {url}]\n{block}")

    return "\n\n".join(tagged_blocks)


DEFAULT_RELEVANCY_PROMPT_TEMPLATE = PromptTemplate(
    template="""As a grader, your task is to evaluate the relevance of a document retrieved in response to a user's question.

    Retrieved Document:
    -------------------
    {context_str}

    User Question:
    --------------
    {query_str}

    Evaluation Criteria:
    - Consider whether the document contains keywords or topics related to the user's question.
    - The evaluation should not be overly stringent; the primary objective is to identify and filter out clearly irrelevant retrievals.

    Decision:
    - Assign a binary score to indicate the document's relevance.
    - Use 'yes' if the document is relevant to the question, or 'no' if it is not.

    Please provide your binary score ('yes' or 'no') below to indicate the document's relevance to the user question."""
)

DEFAULT_TRANSFORM_QUERY_TEMPLATE = PromptTemplate(
    template="""Your task is to refine a query to ensure it is highly effective for retrieving relevant search results. \n
    Analyze the given input to grasp the core semantic intent or meaning. \n
    Original Query:
    \n ------- \n
    {query_str}
    \n ------- \n
    Your goal is to rephrase or enhance this query to improve its search performance. Ensure the revised query is concise and directly aligned with the intended search objective. \n
    Respond with the optimized query only:"""
)

DEFAULT_CRITIQUE_PROMPT_TEMPLATE = PromptTemplate(
    template="""You are fact-checking an AI-generated answer against the context it was supposed to be based on.

    Context:
    -------------------
    {context_str}

    Answer to check:
    -------------------
    {answer}

    Task: identify any factual claims in the answer that are NOT supported by
    the context above - fabricated, unsupported, or contradicted. Reasonable
    synthesis, summarization, or rephrasing of what the context says is fine;
    only flag claims the context does not actually back up.

    If every claim is supported, respond with exactly: SUPPORTED
    Otherwise, respond with a short bullet list of the specific unsupported
    claims and nothing else."""
)


class CorrectiveRAGWorkflow(Workflow):
    """Corrective RAG Workflow."""

    # Minimum fraction of retrieved nodes that must be graded "yes" (relevant)
    # before we trust local retrieval alone. This mirrors the CRAG paper's
    # tiered decision (mostly-relevant -> answer directly, mostly-irrelevant
    # -> web search, mixed -> a blend) instead of triggering a full web
    # search the moment a single node out of many is graded "no". 0.7 was
    # picked as a starting point that tolerates a minority of noisy/irrelevant
    # chunks (common with naive top-k retrieval) while still catching cases
    # where retrieval genuinely missed the topic. Tune as needed.
    RELEVANCE_TRIGGER_THRESHOLD = 0.7

    def __init__(
        self,
        index,
        firecrawl_api_key: str,
        llm: Optional[LLM] = None,
        **kwargs: Any
    ) -> None:
        """Init params."""
        super().__init__(**kwargs)
        self.index = index
        self.firecrawl_api_key = firecrawl_api_key
        
        self.llm = llm if llm is not None else build_llm()
        
        # Set the global LLM settings to avoid conflicts
        from llama_index.core import Settings
        Settings.llm = self.llm

    @step
    async def retrieve(self, ctx: Context, ev: StartEvent) -> Optional[RetrieveEvent]:
        """Retrieve the relevant nodes for the query."""
        query_str = ev.get("query_str")
        retriever_kwargs = ev.get("retriever_kwargs", {})

        print(f"DEBUG: retrieve - query_str: {query_str}")
        print(f"DEBUG: retrieve - retriever_kwargs: {retriever_kwargs}")

        if query_str is None:
            print("DEBUG: retrieve - query_str is None, returning None")
            return None

        retriever: BaseRetriever = self.index.as_retriever(**retriever_kwargs)
        print(f"DEBUG: retrieve - retriever created: {type(retriever)}")
        
        result = retriever.retrieve(query_str)
        print(f"DEBUG: retrieve - retrieved {len(result)} nodes")
        
        if result:
            print(f"DEBUG: retrieve - first node preview: {result[0].text[:100]}...")
        
        await ctx.set("retrieved_nodes", result)
        await ctx.set("query_str", query_str)
        return RetrieveEvent(retrieved_nodes=result)

    async def _grade_node_relevance(self, i: int, node, query_str: str) -> str:
        """Grade a single retrieved node's relevance to the query.

        This is designed to be safe to run concurrently with asyncio.gather:
        it never raises. If the async LLM call fails, it falls back to a
        synchronous call (same behavior as before); if that also fails, the
        node is conservatively graded "no" rather than blowing up the whole
        gather over one bad node.
        """
        prompt = DEFAULT_RELEVANCY_PROMPT_TEMPLATE.format(
            context_str=node.text, query_str=query_str)
        try:
            relevancy = await self.llm.acomplete(prompt)
            print(f"DEBUG: Node {i} relevancy: {relevancy.text}")
            return relevancy.text.lower().strip()
        except Exception as e:
            try:
                # Fallback to synchronous call if async is not supported
                relevancy = self.llm.complete(prompt)
                print(f"DEBUG: Node {i} relevancy (sync fallback): {relevancy.text}")
                return relevancy.text.lower().strip()
            except Exception as e2:
                print(f"DEBUG: Node {i} relevancy grading failed ({e2!r}), treating as 'no'")
                return "no"

    @step
    async def eval_relevance(
        self, ctx: Context, ev: RetrieveEvent
    ) -> WebSearchEvent | QueryEvent:
        """Evaluate relevancy of retrieved documents with the query."""
        retrieved_nodes = ev.retrieved_nodes
        query_str = await ctx.get("query_str")

        print(f"DEBUG: Retrieved {len(retrieved_nodes)} nodes")
        print(f"DEBUG: Query: {query_str}")

        for i, node in enumerate(retrieved_nodes):
            print(f"DEBUG: Node {i} text preview: {node.text[:100]}...")

        # Grade all nodes concurrently instead of one LLM call at a time -
        # grading N nodes now takes roughly the latency of ONE call instead
        # of N sequential calls. gather() preserves input order in its
        # results regardless of completion order, so relevancy_results[i]
        # still lines up with retrieved_nodes[i].
        print(f"DEBUG: Grading {len(retrieved_nodes)} nodes concurrently")
        relevancy_results = await asyncio.gather(
            *(
                self._grade_node_relevance(i, node, query_str)
                for i, node in enumerate(retrieved_nodes)
            )
        )

        print(f"DEBUG: All relevancy results: {relevancy_results}")

        relevancy_results_striped = [re.sub(r"<think>.*?</think>", "", s, flags=re.DOTALL).strip() for s in relevancy_results]

        # Improved relevancy parsing - look for "yes" anywhere in the response
        relevant_texts = [
            retrieved_nodes[i].text
            for i, result in enumerate(relevancy_results_striped)
            if "yes" in result.lower()
        ]
        print(f"DEBUG: Relevant texts count: {len(relevant_texts)}")
        if relevant_texts:
            print(f"DEBUG: First relevant text preview: {relevant_texts[0][:200]}...")

        # Confidence-tiered decision (CRAG-style) instead of a binary "any
        # node graded 'no' triggers a full web search": only fall back to
        # web search when the fraction of relevant nodes drops below
        # RELEVANCE_TRIGGER_THRESHOLD. This avoids nuking a mostly-good
        # retrieval (e.g. 9/10 relevant) just because one node was noisy.
        num_nodes = len(retrieved_nodes)
        relevant_fraction = (len(relevant_texts) / num_nodes) if num_nodes else 0.0
        print(
            f"DEBUG: Relevant fraction: {relevant_fraction:.2f} "
            f"(threshold: {self.RELEVANCE_TRIGGER_THRESHOLD})"
        )

        if relevant_fraction < self.RELEVANCE_TRIGGER_THRESHOLD:
            print("DEBUG: Relevant fraction below threshold, returning WebSearchEvent")
            return WebSearchEvent(relevant_chunks=relevant_texts)
        else:
            print("DEBUG: Relevant fraction meets threshold, returning QueryEvent")
            return QueryEvent(relevant_chunks=relevant_texts, search_text="")

    def _firecrawl_search(self, query: str, limit: int = 5) -> str:
        """Perform web search using FireCrawl API directly."""
        url = "https://api.firecrawl.dev/v1/search"
        
        payload = {
            "query": query,
            "limit": 5,
            "timeout": 60000,
        }
        
        headers = {
            "Authorization": f"Bearer {self.firecrawl_api_key}",
            "Content-Type": "application/json"
        }
        
        try:
            response = requests.post(url, json=payload, headers=headers, timeout=60)
            response.raise_for_status()
            
            data = response.json()
            
            if data.get("success") and data.get("data"):
                # Extract title and description from each result
                search_results = []
                for result in data["data"]:
                    title = result.get("title", "")
                    description = result.get("description", "")
                    url = result.get("url", "")
                    
                    if title or description:
                        result_text = f"Title: {title}\nDescription: {description}\nURL: {url}\n"
                        search_results.append(result_text)
                
                return "\n---\n".join(search_results)
            else:
                print(f"DEBUG: FireCrawl API returned no results or error: {data}")
                return ""
                
        except requests.exceptions.RequestException as e:
            print(f"DEBUG: FireCrawl API request failed: {e}")
            return ""
        except Exception as e:
            print(f"DEBUG: Unexpected error in FireCrawl search: {e}")
            return ""

    @step
    async def web_search(
        self, ctx: Context, ev: WebSearchEvent
    ) -> QueryEvent:
        """Search the transformed query"""
        # If any document is found irrelevant, transform the query string for better search results.

        query_str = await ctx.get("query_str")

        prompt = DEFAULT_TRANSFORM_QUERY_TEMPLATE.format(query_str=query_str)
        try:
            result = await self.llm.acomplete(prompt)
            transformed_query_str = result.text
        except Exception as e:
            # Fallback to synchronous call if async is not supported
            result = self.llm.complete(prompt)
            transformed_query_str = result.text
            
        print(f"DEBUG: web_search - transformed query: {transformed_query_str}")
        
        # Conduct a search with the transformed query string using direct API call
        raw_search_text = self._firecrawl_search(transformed_query_str)

        # Tag each result block with its source URL so query_result() can
        # attribute context (and the model can cite it) instead of blending
        # everything into one anonymous blob.
        search_text = _tag_web_search_results(raw_search_text)

        print(f"DEBUG: web_search - search results length: {len(search_text)}")
        if search_text:
            print(f"DEBUG: web_search - search results preview: {search_text[:200]}...")

        return QueryEvent(relevant_chunks=ev.relevant_chunks, search_text=search_text)

    @step
    async def query_result(self, ctx: Context, ev: QueryEvent) -> StopEvent:
        """Generate the final answer, streaming it, tagging its sources with
        the exact chunk each one contributed, and fact-checking the finished
        answer against that same context.

        The context handed to the LLM is tagged per-source ("[Document Source]"
        for retrieved text, "[Web Source: <url>]" per web result - the latter
        already tagged by web_search()) and the prompt asks the model to end
        its answer with a "Sources:" section naming what it actually used.
        We also independently track which sources were *available* (not just
        what the model claims to have used) and return them alongside the
        answer, each carrying the exact snippet it corresponds to - not just
        a generic "Uploaded source" label - so app.py can show the user
        precisely what backed a claim instead of asking them to trust it.

        The answer itself is generated with `llm.astream_complete()` so tokens
        can be pushed to the caller as they arrive via
        `ctx.write_event_to_stream(TokenEvent(...))` - see app.py's
        `run_workflow()`, which consumes these through
        `handler.stream_events()`. Workflow.run() only resolves once a
        StopEvent is produced, so the full assembled text is also returned
        there for callers that just want the final answer.

        After the answer is fully generated, one more (non-streamed) LLM call
        re-checks it against the same context for claims the context doesn't
        actually support - a lightweight self-critique pass, separate from
        the relevance grading that decided what context to use in the first
        place. It never blocks or rewrites the answer, only annotates it:
        the point is to surface doubt, not to silently hide it.
        """
        relevant_chunks = ev.relevant_chunks
        search_text = ev.search_text
        query_str = await ctx.get("query_str")

        print(f"DEBUG: query_result - query_str: {query_str}")
        print(f"DEBUG: query_result - relevant_chunks: {len(relevant_chunks)}")
        print(f"DEBUG: query_result - search_text: {search_text}")

        if not relevant_chunks and not search_text.strip():
            print("DEBUG: No relevant text, returning empty response")
            return StopEvent(
                result={
                    "answer": "No relevant information found in the documents.",
                    "sources": [],
                    "critique": None,
                }
            )

        context_parts = []
        sources: list[dict] = []

        if relevant_chunks:
            context_parts.append(
                "[Document Source]\n" + "\n\n".join(c.strip() for c in relevant_chunks)
            )
            for chunk in relevant_chunks:
                sources.append({"type": "document", "text": chunk.strip()})

        if search_text.strip():
            context_parts.append(search_text.strip())
            seen_urls = set()
            for block in search_text.split("\n\n"):
                match = re.match(r"\[Web Source:\s*(\S+)\]\n(.*)", block.strip(), re.DOTALL)
                if not match:
                    continue
                url, text = match.group(1), match.group(2)
                if url not in seen_urls:
                    seen_urls.add(url)
                    sources.append({"type": "web", "url": url, "text": text.strip()})

        context_str = "\n\n".join(context_parts)

        prompt = f"""As a helpful assistant, your task is to answer the user's question based on the given context.

        A few things to keep in mind:
        - The context is made up of clearly labeled sources: text prefixed with "[Document Source]" comes from the uploaded document, and text prefixed with "[Web Source: <url>]" comes from a web search result at that URL.
        - The context can be a mix of both kinds of sources, or just one.

        Your task is to look at the query and the whole context and generate what you think is the best answer to the question.

        Here is the context:
        Context:
        {context_str}

        --------------------------------

        Question:
        {query_str}

        --------------------------------

        Generate an answer to the question. Then add a final section titled "Sources:" that lists which of the labeled sources above you actually drew on (e.g. "Document" and/or the specific web URL(s)). Only list sources you actually used.
        """

        full_response = ""
        try:
            response_gen = await self.llm.astream_complete(prompt)
            async for chunk in response_gen:
                delta = chunk.delta or ""
                if delta:
                    full_response += delta
                    # Not awaited: write_event_to_stream() is a plain sync
                    # call that enqueues onto the handler's event stream.
                    ctx.write_event_to_stream(TokenEvent(delta=delta))
        except Exception as e:
            # Fallback to a single non-streaming call if streaming isn't
            # supported by whatever LLM was configured (mirrors the sync
            # fallback pattern used elsewhere in this workflow). The caller
            # still gets the full answer, just not token-by-token.
            print(f"DEBUG: query_result - streaming failed ({e!r}), falling back to acomplete")
            result = await self.llm.acomplete(prompt)
            full_response = result.text
            if full_response:
                ctx.write_event_to_stream(TokenEvent(delta=full_response))

        print(f"DEBUG: query_result - final result: {full_response}")

        critique = await self._critique_answer(context_str, full_response)

        return StopEvent(result={"answer": full_response, "sources": sources, "critique": critique})

    async def _critique_answer(self, context_str: str, answer: str) -> Optional[dict]:
        """Fact-check the finished answer against the same context it was
        generated from, and return `{"passed": bool, "note": str | None}` -
        or None if the check itself couldn't be run (never let a critique
        failure take down the answer that already streamed to the user).

        Deliberately a separate, non-streamed call after the answer is
        complete rather than folded into the generation prompt: asking a
        model to write an answer and grade its own answer in the same
        breath is much less reliable than a second, independent pass.
        """
        if not answer.strip():
            return None
        try:
            prompt = DEFAULT_CRITIQUE_PROMPT_TEMPLATE.format(context_str=context_str, answer=answer)
            try:
                result = await self.llm.acomplete(prompt)
            except Exception:
                result = self.llm.complete(prompt)
            critique_text = re.sub(r"<think>.*?</think>", "", result.text, flags=re.DOTALL).strip()
        except Exception as e:
            print(f"DEBUG: critique pass failed ({e!r}), skipping")
            return None

        passed = not critique_text or critique_text.upper().startswith("SUPPORTED")
        print(f"DEBUG: critique - passed={passed} text={critique_text[:200]}")
        return {"passed": passed, "note": None if passed else critique_text}
